# Generated by Django 2.2.2 on 2020-03-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortendb',
            name='shortcode',
            field=models.CharField(default='codes', max_length=10),
            preserve_default=False,
        ),
    ]
