# Generated by Django 2.2.2 on 2020-03-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortener', '0002_shortendb_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortendb',
            name='shortcode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
