# Generated by Django 2.2.2 on 2020-03-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortener', '0003_auto_20200305_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortendb',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
