# Generated by Django 2.2.2 on 2020-03-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortener', '0004_shortendb_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortendb',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
