# Generated by Django 2.2.2 on 2020-03-06 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortener', '0006_auto_20200306_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortendb',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
